### ISSUE TITLE
Problemas com o builder

### ISSUE THREAD

**Issue by Eufranio** [FabioZumbi12/UltimateChat#14]
No chat global, uso as tags padrões, mas no local eu ia usar como o LegendChat (a mensagem amarela). Eu criei um builder novo de mensagem só pra o chat local:
```
  messagelocal:
    format: '&e{message}'
    click-cmd: ''
    hover-messages: []
    show-in-worlds: []
    hide-in-worlds: []
```
E nas configurações do canal, ele *deveria* usar esse builder em vez do padrão:
```
name: Local
alias: L
across-worlds: false
distance: 40
cost: 0
color: '&e'
need-focus: false
receivers-message: true
tag-builder: ch-tags,group-preffix,nickname,group-suffix,messagelocal
```
Mas a mensagem continua sendo enviada normalmente, sem alguma modificação. Alguma ideia?
