### ISSUE TITLE
[BUG] Som no anúncio de mensagens automáticas

### ISSUE THREAD

**Issue by SrBedrock** [FabioZumbi12/UltimateChat#215]
Adicionar som para cada mensagem enviada automática.
O ideal seria uma opção para cada mensagem, mas a opção para todas as mensagens também estaria de bom tamanho na minha opinião.
Exemplo:

```
enable: true
silent: true
playsound: 'note_pling'
interval: 300
messages:
  '0':
    minPlayers: 1
    text: '&a&lDICA! &rDigite &a/discord &fe acesse o discord do servidor!'
    hover: Clique aqui para acessar o discord!
    url: https://discord.gg/gv7Gdea
```
