### ISSUE TITLE
Tags personalizadas no chat

### ISSUE THREAD

**Issue by Hu3diger** [FabioZumbi12/UltimateChat#25]
Olá,

Primeiramente queria parabenizar por este plugin sensacional!!

Mas então,
Tenho alguns plugins que adicionam tags ao ganhar o evento (Gladiador, etc).
Logo, no outro plugin de chat que eu utilizava, bastava colocar {gladiador} que funcionava.

Gostaria de saber como que faço isto no UChat.

Desde já agradeço

**Comment by Mike5357** [comment]
Eu traduzi o seu problema para o inglês através do Google traduzir para entender o seu problema, mas pensei que poderia ser de alguma ajuda:

You could have the {Gladiator} tag added in tags section of the config.yml like this:
```
  gladiatorprefix:
    format: '&8{&6Gladiator&8}'
    hover-messages:
    - '&cWon from an event!'
    permission: **ultimatechat.gladiatorprefix**
```

then you would just go into your tag-builder and add in the permission like this: 
tag-builder: ch-tags,group-prefix,**gladiatorprefix**,nickname,group-suffix,message

Hope this helped!
