### ISSUE TITLE
No command excuted. (auto broadcast)

### ISSUE THREAD

**Issue by DutchUser** [FabioZumbi12/UltimateChat#93]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  **Spigot** > 1.12.2

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b138-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Well.. That if you click on it it excute the command.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Not any error.

https://pastebin.com/wEznZJcW

I also tried using just /msg (an essentialsX command) but that also does nothing.

**Comment by FabioZumbi12** [comment]
Reproduced here and works fine:

```
enable: true
interval: 114
silent: true
messages:
  '0':
    minPlayers: 2
    text: '&7[&rArea&bZ&e1&72]&r &cRegras do server atualizadas. Clique aqui!'
    hover: '&4Clique para ver!'
    onclick: ''
    suggest: ''
    url: http://areaz12server.net.br/regras-do-servidor/
  '1':
    minPlayers: 2
    text: '&7[&rArea&bZ&e1&72]&r &5Nosso THE END reseta toda semana, de Domingo pra
      Segunda!'
    hover: '&5Clique aqui para ir para os portais'
    onclick: warp portal
    suggest: ''
    url: ''
```
Both `url` and `on-click` works, the player is teleported to `warp portal` and on `1` open the url dialog to go to site.

I see on your paste, enable is `false`, need to be true to work.
btw, try with latest dev build 146 from our jenkins.
